# Generated by Django 3.2.8 on 2022-01-29 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogpost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('category', models.CharField(choices=[('choice1', 'Choice1'), ('choice2', 'Choice2'), ('choice3', 'Choice3'), ('choice4', 'Choice4')], default='choice1', max_length=50)),
                ('excerpt', models.CharField(max_length=150)),
                ('thumbnail', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('month', models.CharField(max_length=3)),
                ('day', models.CharField(max_length=2)),
                ('content', models.TextField()),
                ('featured', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
